version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: koa_app
    image: koa-app
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/home/www/app
      - ./nginx/conf/nginx.conf:/home/www/nginx/conf/nginx.conf
      - ./nginx/vhost.conf:/home/www/nginx/vhost.conf
    environment:
      APP_MAILER_FROM: ${APP_MAILER_FROM}
      APP_MAILER_SMTP_ADDRESS: ${APP_MAILER_SMTP_ADDRESS}
      APP_MAILER_SMTP_PORT: ${APP_MAILER_SMTP_PORT}
      APP_MAILER_SMTP_USERNAME: ${APP_MAILER_SMTP_USERNAME}
      APP_MAILER_SMTP_PASSWORD: ${APP_MAILER_SMTP_PASSWORD}
      APP_MONGO: ${APP_MONGO}
      APP_REDIS_MASTER: ${APP_REDIS_MASTER}
      APP_SECRET_KEY_BASE: ${APP_SECRET_KEY_BASE}
      APP_SESSION_KEY: ${APP_SESSION_KEY}
      APP_SESSION_DOMAIN: ${APP_SESSION_DOMAIN}
