koa_app:
  container_name: koa_app
  image: ${APP_IMAGE_HOST}/koa-app:latest
  restart: always
  ports:
    - 3000:3000
  volumes:
    - ./log:/home/node/app/log
    - ./tmp:/home/node/app/tmp
  environment:
    NODE_ENV: ${NODE_ENV}
    APP_MAILER_FROM: ${APP_MAILER_FROM}
    APP_MAILER_SMTP_ADDRESS: ${APP_MAILER_SMTP_ADDRESS}
    APP_MAILER_SMTP_PORT: ${APP_MAILER_SMTP_PORT}
    APP_MAILER_SMTP_USERNAME: ${APP_MAILER_SMTP_USERNAME}
    APP_MAILER_SMTP_PASSWORD: ${APP_MAILER_SMTP_PASSWORD}
    APP_MONGO: ${APP_MONGO}
    APP_REDIS_MASTER: ${APP_REDIS_MASTER}
    APP_SECRET_KEY_BASE: ${APP_SECRET_KEY_BASE}
    APP_SESSION_KEY: ${APP_SESSION_KEY}
    APP_SESSION_DOMAIN: ${APP_SESSION_DOMAIN}
